repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        args: [ '--maxkb=2000' ]
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: pretty-format-json
        args: [ '--autofix', '--no-sort-keys' ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        args: [ "--install-types", "--non-interactive", "--ignore-missing-imports" ]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.7
    hooks:
      # Run the linter
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix, --output-format=full ]
      # Run the formatter
      - id: ruff-format
