technology_category_to_CTS_field = {
    "BoilerPlantImprovements": "A_Uncategorized",
    "ChillerPlantImprovements": "B_Uncategorized",
    "BuildingAutomationSystems": "C_Uncategorized",
    "OtherHVAC": "D_Uncategorized",
    "LightingImprovements": "E_Uncategorized",
    "BuildingEnvelopeModifications": "F_Uncategorized",
    "ChilledWaterHotWaterAndSteamDistributionSystems": "G_Uncategorized",
    "ConveyanceSystems": "V_Uncategorized",
    "OtherElectricMotorsAndDrives": "H_Uncategorized",
    "Refrigeration": "I_Uncategorized",
    "DistributedGeneration": "J_Uncategorized",
    "RenewableEnergySystems": "K_Uncategorized",
    "EnergyDistributionSystems": "L_Uncategorized",
    "ServiceHotWaterSystems": "U_Uncategorized",
    "WaterAndSewerConservationSystems": "M_Uncategorized",
    "ElectricalPeakShavingLoadShifting": "N_Uncategorized",
    "EnergyCostReductionThroughRateAdjustments": "O_Uncategorized",
    "EnergyRelatedProcessImprovements": "P_Uncategorized",
    "AdvancedMeteringSystems": "Q_Uncategorized",
    "PlugLoadReductions": "R_Uncategorized",
    # "DataCenterImprovements": "_Uncategorized",
    # "AlternativeWaterSources": "_Uncategorized",
    "KitchenImprovements": "W_Uncategorized",
    # "LaboratoryAndMedicalEquipments": "_Uncategorized",
    # "IrrigationSystemsAndLandscapingImprovements": "_Uncategorized",
    # "WashingEquipmentsAndTechiques": "_Uncategorized",
    # "FutureOtherECMs": "_Uncategorized",
    # # "HealthAndSafety": "_Uncategorized",
    "Uncategorized": "T_Uncategorized",
}
