building_occ_class_to_building_type = {
    'Assembly-Convention center': 'Convention center',
    'Assembly-Cultural entertainment': 'Performing arts theater',
    'Assembly-Indoor arena': 'Sports Arena',
    'Assembly-Race track': 'Sports Arena',
    'Assembly-Religious': 'Religious building',
    'Assembly-Social entertainment': 'Performing arts theater',
    'Assembly-Stadium': 'Gymnasium',
    'Assembly-Stadium (closed)': 'Gymnasium',
    'Assembly-Stadium (open)': 'Gymnasium',
    'Bar': 'Dining: Bar Lounge/Leisure',
    'Bar-Nightclub': 'Dining: Bar Lounge/Leisure',
    'Convenience store': 'Retail',
    'Courthouse': 'Court house',
    'Education': 'School/University',
    'Education-Adult': 'School/University',
    'Education-Higher': 'School/University',
    'Education-Preschool or daycare': 'School/University',
    'Education-Primary': 'School/University',
    'Education-Secondary': 'School/University',
    'Education-Vocational': 'School/University',
    'Food service': 'Dining: Cafeteria/Fast Food',
    'Food service-Fast': 'Dining: Cafeteria/Fast Food',
    'Food service-Full': 'Dining: Family',
    'Food service-Institutional': 'Dining: Cafeteria/Fast Food',
    'Food service-Limited': 'Dining: Cafeteria/Fast Food',
    'Health care': 'Hospital',
    'Industrial': 'Manufacturing Facility',
    'Industrial manufacturing plant': 'Manufacturing facility',
    'Lodging': 'Hotel',
    'Lodging with extended amenities': 'Hotel',
    'Lodging with limited amenities': 'Motel',
    'Lodging-Barracks': 'Domitory',
    'Lodging-Institutional': 'Domitory',
    'Mixed-use commercial': 'Office',
    'Multifamily': 'Multi-Family',
    'Multifamily with commercial': 'Multi-Family',
    'Office': 'Office',
    'Parking': 'Parking Garage',
    'Public safety': 'Police station',
    'Public safety station': 'Police station',
    'Public safety station-Fire': 'Fire Station',
    'Public safety station-Police': 'Police station',
    'Public safety-Correctional facility': 'Penitentiary',
    'Public safety-Detention center': 'Penitentiary',
    'Recreation': 'Exercise Center',
    'Recreation-Bowling alley': 'Exercise Center',
    'Recreation-Fitness center': 'Exercise Center',
    'Recreation-Ice rink': 'Exercise Center',
    'Recreation-Indoor sport': 'Exercise Center',
    'Recreation-Pool': 'Exercise Center',
    'Recreation-Roller rink': 'Exercise Center',
    'Retail': 'Retail',
    'Retail-Automobile dealership': 'Automotive Facility',
    'Retail-Dry goods retail': 'Retail',
    'Retail-Enclosed mall': 'Retail',
    'Retail-Hypermarket': 'Retail',
    'Retail-Mall': 'Retail',
    'Retail-Strip mall': 'Retail',
    'Service-Postal': 'Post Office',
    'Service-Production and assembly': 'Manufacturing Facility',
    'Service-Repair': 'Manufacturing Facility',
    'Transportation terminal': 'Transportation',
    'Warehouse': 'Warehouse',
    'Warehouse-Refrigerated': 'Warehouse',
    'Warehouse-Self-storage': 'Warehouse',
    'Warehouse-Unrefrigerated': 'Warehouse'
 }
