section_occ_class_to_section_type = {
    'Atrium': 'Atrium',
    'Auditorium': 'Audience Seating Area',
    'Chemical storage room': 'Storage Room',
    'Classroom': 'Classroom/Lecture Hall',
    'Computer lab': 'Computer Room',
    'Conference room': 'Conference/Meeting',
    'Corridor': 'Corridor',
    'Courtroom': 'Courtroom',
    'Dining area': 'Dining Area',
    'Dressing area': 'Dressing Room',
    'Food sales-Grocery store': 'Sales Area',
    'Health care-Inpatient hospital': 'Patient room',
    'Health care-Outpatient facility': 'Emergency',
    'Health care-Outpatient rehabilitation': 'Recovery',
    'Health care-Outpatient surgical': 'Operating room',
    'Health care-Pharmacy': 'Pharmacy',
    'Health care-Residential treatment center': 'Exam/treatment',
    'Health care-Skilled nursing facility': 'Nursery',
    'Kitchen': 'Food Preparation Area',
    'Kitchenette': 'Food Preparation Area',
    'Laboratory': 'Laboratory',
    'Laboratory-Medical': 'Laboratory',
    'Laboratory-Testing': 'Laboratory',
    'Laundry area': 'Laundry/Washing Area',
    'Living area': 'Living Quarters',
    'Lobby': 'Lobby',
    'Lodging area': 'Living Quarters',
    'Mechanical room': ' Electrical/Mechanical Room',
    'Non-chemical storage room': 'Storage Room',
    'Office': 'Office',
    'Office work area': 'Office',
    'Office-Financial': 'Office',
    'Parking': 'Parking Area',
    'Printing room': 'Copy/Print Room',
    'Recreation-Bowling alley': 'Playing area',
    'Recreation-Fitness center': 'Exercise area',
    'Recreation-Ice rink': 'Playing area',
    'Recreation-Indoor sport': 'Playing area',
    'Recreation-Pool': 'Playing area',
    'Recreation-Roller rink': 'Playing area',
    'Refrigerated storage': 'Storage Room',
    'Restroom': 'Restroom',
    'Service-Laundry or dry cleaning': 'Laundry/Washing Area',
    'Service-Postal': 'Sorting Area?',
    'Service-Production and assembly': 'multiple categories under Manufacturing Facility',
    'Shipping and receiving': 'Sorting Area',
    'Sleeping area': 'Sleeping Quarters',
    'Spectator area': 'Audience Seating Area',
    'Sport play area': 'Playing Area',
    'Transportation waiting area': 'Audience Seating Area',
    'Warehouse': 'Storage Area',
    'Warehouse-Refrigerated': 'Storage Area',
    'Warehouse-Self-storage': 'Storage Area',
    'Warehouse-Unrefrigerated': 'Storage Area'
 }
