electric_fuel_types = [
    "Electricity",
    "Electricity-Exported",
    "Electricity-Onsite generated",
    "Hydropower",
    "Biofuel",
    "Biofuel B5",
    "Biofuel B10",
    "Biofuel B20",
    "Wind",
    "Geothermal",
    "Solar",
    "Biomass",
    "Hydrothermal",
    "Dry steam",
    "Flash steam",
    "Ethanol",
    "Biodiesel",
    "Waste heat",
    "Dual fuel",
    "Thermal-Exported",
    "Thermal-Onsite generated",
    "Other delivered-Exported",
    "Other delivered-Onsite generated",
    "Other metered-Exported",
    "Other metered-Onsite generated",
    "Other",
    "Unknown",
]
