name: CI

on:
  pull_request:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.9", "3.12" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 1.8.3
      - name: Setup Python
        run: |
          pip install --upgrade pip
          poetry install
      - name: Run tests
        run: |
          poetry run pytest
  formatting:
    name: Pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
      - name: Install poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 1.8.3
      - name: type check
        run: |
          poetry install
          poetry run mypy .
